
on: pull_request

changelog:
  categories:
    - title: ğŸ• Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: ğŸ‘’ Dependencies
      labels:
        - dependencies
